import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavOpenAndThemeProvider } from "./components/general/NavOpenAndThemeProvider";
import MobileNav from "./components/general/MobileNav";
import Sidebar from "./components/general/Sidebar";

export const metadata: Metadata = {
  title: "Purity UI Dahboard by Creative Tim & Simmmple ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-pry text-textCol overflow-x-hidden">
        <NavOpenAndThemeProvider>
          <div className="flex min-h-screen pt-7">
            <Sidebar />
            <main className="flex-1 lg:ml-[270px] ">
              <MobileNav />
              {children}
            </main>
          </div>
        </NavOpenAndThemeProvider>
      </body>
    </html>
  );
}
