import type { Metadata } from "next";
import "./globals.css";
import { NavOpenAndThemeProvider } from "./components/general/NavOpenAndThemeProvider";

export const metadata: Metadata = {
  title: "Purity UI Dahboard by Creative Tim & Simmmple ",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavOpenAndThemeProvider>
        <body className="bg-pry text-textCol">{children}</body>
      </NavOpenAndThemeProvider>
    </html>
  );
}
