import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { NavOpenAndThemeProvider } from "@/app/components/general/NavOpenAndThemeProvider";
import Sidebar from "@/app/components/general/Sidebar";
import MobileNav from "@/app/components/general/MobileNav";
import Footer from "@/app/components/general/Footer";

export const metadata: Metadata = {
  title: "Purity UI Dahboard by Creative Tim & Simmmple ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-pry text-textCol">
      <div className="flex min-h-screen pt-7">
        <Sidebar />
        <main className="flex-1 relative  w-[calc(100%-250px)] lg:ml-[250px] overflow-x-auto ">
          <MobileNav />
          <div className="mt-12">{children}</div>

          <Footer />
        </main>
      </div>
    </div>
  );
}
